[package]
name = "matrust"
version = "0.0.3"
description="A simple and small f64 matrix lib"
keywords=["matrix"]
license="MIT"
repository="https://github.com/mikkelkai/matrust"
authors = ["mikkelkai <mikkelkai@gmail.com>"]

[dependencies]
rand = "0.3"